system:
  name: EdgeFlex RoboClaw
  id: edgeflex
  web_interface: edgeflex.html

driver:
  type: roboclaw
  device: /dev/ttyACM0
  baud_rate: 115200
  address: 128
  loop_hz: 10
  deadman_secs: 3

motors:
- name: left
  max_speed: 10000
  default_speed: 5000
  max_accel: 8000
  invert: false
- name: right
  max_speed: 10000
  default_speed: 5000
  max_accel: 8000
  invert: true
